In [9]:
import cv2

face_cascade = cv2.CascadeClassifier('C:/Users/Vicky Kumar/Desktop/face detection attendence file/haarcascade_frontalface_default.xml')

img = cv2.imread('C:/Users/Vicky Kumar/Pictures/Camera Roll/WIN_20200118_01_34_08_Pro.jpg',1)

# Black and White (gray scale)
# img_bw = cv2.imread ('C:/Users/Vicky Kumar/Pictures/Camera Roll/WIN_20200118_01_34_08_Pro.jpg',0)
img_bw = cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

faces = face_cascade.detectMultiScale(img_bw, scaleFactor = 1.05, minNeighbors = 5)

for x,y,w,h in faces:
    img = cv2.rectangle(img, (x,y), (x+w,y+h), (0,155,0), 3)

In [2]:
faces

array([[519, 214, 351, 351]], dtype=int32)

In [3]:
print(img.shape)
img

(720, 1280, 3)


array([[[193, 212, 195],
        [192, 211, 194],
        [192, 210, 193],
        ...,
        [255, 254, 253],
        [255, 254, 253],
        [255, 254, 253]],

       [[193, 212, 195],
        [193, 212, 195],
        [193, 211, 194],
        ...,
        [255, 254, 253],
        [255, 254, 253],
        [255, 254, 253]],

       [[194, 213, 196],
        [194, 213, 196],
        [194, 212, 195],
        ...,
        [255, 254, 253],
        [255, 254, 253],
        [255, 254, 253]],

       ...,

       [[122, 142, 130],
        [123, 143, 131],
        [125, 145, 133],
        ...,
        [  8,   0,   0],
        [ 10,   0,   0],
        [ 10,   0,   0]],

       [[118, 140, 128],
        [119, 141, 129],
        [123, 143, 131],
        ...,
        [  8,   0,   0],
        [ 10,   0,   0],
        [ 10,   0,   0]],

       [[116, 138, 126],
        [118, 140, 128],
        [122, 142, 130],
        ...,
        [  8,   0,   0],
        [ 10,   0,   0],
        [ 10,   0,   0]]

In [4]:
print(img_bw.shape)
img_bw

(720, 1280)


array([[205, 204, 203, ..., 254, 254, 254],
       [205, 205, 204, ..., 254, 254, 254],
       [206, 206, 205, ..., 254, 254, 254],
       ...,
       [136, 137, 139, ...,   1,   1,   1],
       [134, 135, 137, ...,   1,   1,   1],
       [132, 134, 136, ...,   1,   1,   1]], dtype=uint8)

In [5]:
resized = cv2.resize(img, (int(img.shape[1]/2),int(img.shape[0]/2)))
print(type(resized))
print(resized.shape)

cv2.imshow('WIN_20200118_01_34_08_Pro.jpg',resized)
# cv2.waitKey(2000)
cv2.waitKey(0)
cv2.destroyAllWindows()

<class 'numpy.ndarray'>
(360, 640, 3)


In [6]:
resized_bw = cv2.resize(img_bw, (int(img_bw.shape[1]/3),int(img_bw.shape[0]/3)))
print(type(resized_bw))
print(resized_bw.shape)

cv2.imshow('WIN_20200118_01_34_08_Pro.jpg',resized_bw)
# cv2.waitKey(2000)
cv2.waitKey(0)
cv2.destroyAllWindows()

<class 'numpy.ndarray'>
(240, 426)
